### ISSUE TITLE
Any way to speed up install of licenses?

### ISSUE THREAD

**Issue by Marty** [cirruslabs/docker-images-flutter#115]
My gitlab runner takes quite a few moments for these things:

```
Checking the license for package Android SDK Build-Tools 28.0.3 in /opt/android-sdk-linux/licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
Installing Android SDK Build-Tools 28.0.3 in /opt/android-sdk-linux/build-tools/28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
Checking the license for package Android SDK Platform 28 in /opt/android-sdk-linux/licenses
License for package Android SDK Platform 28 accepted.
Preparing "Install Android SDK Platform 28 (revision: 6)".
"Install Android SDK Platform 28 (revision: 6)" ready.
Installing Android SDK Platform 28 in /opt/android-sdk-linux/platforms/android-28
"Install Android SDK Platform 28 (revision: 6)" complete.
"Install Android SDK Platform 28 (revision: 6)" finished.
Checking the license for package Android SDK Platform 29 in /opt/android-sdk-linux/licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 5)".
"Install Android SDK Platform 29 (revision: 5)" ready.
Installing Android SDK Platform 29 in /opt/android-sdk-linux/platforms/android-29
"Install Android SDK Platform 29 (revision: 5)" complete.
"Install Android SDK Platform 29 (revision: 5)" finished.
```
Is there any way to speed this up, either via caching a certain directory or by doing this when the image is built?

**Comment by Leystryku** [comment]
Can confirm, I am having the same issue.
I believe the Dockerfile needs to
1. Excute flutter precache
2. Somehow Pre-install the Android SDK shit.

**Comment by fkorotkov** [comment]
Could you please provide your YAML configuration?

**Comment by Leystryku** [comment]
Sure, here's mine which causes the same issue within the build stage.

````
image: cirrusci/flutter:stable

stages:
    - build
    - analyze
    - test

before_script:
    - flutter clean
    - flutter pub get


build:
    tags:
        - build
    stage: build
    script:
        - flutter build apk --target-platform android-arm --split-per-abi --release

unit_test:
    tags:
        - test
    stage: test
    script:
        - flutter pub global activate junitreport
        - export PATH=~/.pub-cache/bin:${PATH}
        - flutter test --machine | tojunit > test_report.xml
    artifacts:
        when: always
        reports:
            junit: test_report.xml
analyze:
    tags:
        - analyze
    stage: analyze
    script:
        - flutter analyze

`````
