### ISSUE TITLE
Not working on Azure Pipelines

### ISSUE THREAD

**Issue by damienstanton** [cirruslabs/docker-images-flutter#142]
Hello, I'm trying to use this Docker image (stable) in Azure Pipelines, and the test run fails with the following error:
```console
Flutter failed to open a file at "/sdks/flutter/bin/cache/lockfile".
The flutter tool cannot access the file or directory.
```
The `azure-pipelines.yml` is:
```yml
trigger:
    branches:
        include:
        - main
        - dev/*

pool:
  vmImage: ubuntu-latest
container: 'cirrusci/flutter:stable'

steps:
  - script: flutter test
    displayName: Test
```
Are there any missing env vars or other tricks to get this working? I don't think it's strictly a permissions issue as I see the container should be running as root.
