### ISSUE TITLE
gitlab-CI: WebSocketException: Connection to 'http://127.0.0.1:33655#' was not upgraded to websocket

### ISSUE THREAD

**Issue by boldt** [cirruslabs/docker-images-flutter#158]
**Hint**: I cross-posted this issue also on https://github.com/flutter/flutter/issues/83344, since I don't know whether it's a flutter issue or an issue with the docker-image.

## Environment

* Flutter 2.2.0
* Gitlab CI

## Steps to Reproduce

I created the standard "getting started" app:

```
flutter create flutter_test_mwe
```

On our local machines, we can run `flutter test`, which succeeds:

![grafik](https://user-images.githubusercontent.com/750793/119500140-c0de3000-bd67-11eb-8b6e-5f2c803cc1ba.png)

Now, we want to build the app with gitlab-CI. We're using the image `cirrusci/flutter:2.2.0`:

```
variables:
  FLUTTER_VERSION: 2.2.0

stages:
  - build
  - deploy

build_and_test_job:
  stage: build
  image: cirrusci/flutter:$FLUTTER_VERSION
  script:
    - flutter pub get
    - flutter test
    - flutter build apk
  tags:
    - docker
  only:
    - merge_requests
```

Now, `flutter test`crashes with the error:

> WebSocketException: Connection to 'http://127.0.0.1:33655#' was not upgraded to websocket

![grafik](https://user-images.githubusercontent.com/750793/119500380-06026200-bd68-11eb-9cfe-8af7cebd7c7c.png)

**Comment by fkorotkov** [comment]
Looks more like an issue with your GitLab setup. Will be great if it can be reproduced locally in a docker container. Will be great if you can try `0.0.0.0` and `localhost` instead of `127.0.0.1`.

**Comment by boldt** [comment]
I would like to help you to reproduce this issue.

To do so...
* I would like to unserstand, why "flutter test" tries to open a WebSocket-connection, and 
* How do I configre "flutter test" use another IP?

**Comment by fkorotkov** [comment]
We can try to repro locally in a Docker container by using [Cirrus CLI](https://github.com/cirruslabs/cirrus-cli). Once you install it you can create `.cirrus.yml` in your repo with the following content:

```yaml
env:
  FLUTTER_VERSION: 2.2.0

test_task:
  container:
    image: cirrusci/flutter:$FLUTTER_VERSION
  script:
    - flutter pub get
    - flutter test
    - flutter build apk
```

Once you have it you can try to run `cirrus run` and see if it's working. If it is, it means your host has some issue with Docker configuration and networking. You are using a self-hosted runner, right?
