### ISSUE TITLE
Doesn't work with Dart 2.16.2

### ISSUE THREAD

**Issue by aalex** [cirruslabs/docker-images-flutter#203]
Hi!
Dart 2.16.2 has been released on March 28th, 2022.

To build my Docker image for a Flutter web project, I needed to downgrade our version of Dart in our pubspec.yaml:

```
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
```

By default, when creating a new project, it was `2.16.2`, but then building the Docker image off you base image would not work.
