### ISSUE TITLE
Some Android licenses not accepted.

### ISSUE THREAD

**Issue by lsaudon** [cirruslabs/docker-images-flutter#7]
Hello,

There was no problem before.
Is it a bug or is there a possibility to accept licenses directly in the.gitlab-ci.yml 

```yml
image: cirrusci/flutter

variables:
before_script:
  - flutter channel stable
  - flutter upgrade
  
stages:
  - test
  - build

unitTests:
  stage: test
  script:
    - flutter test

analyze:
  stage: test
  script:
    - flutter analyze

build:
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

```

```
Running flutter doctor...
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```
