### ISSUE TITLE
Circle CI "userns remapping failure"

### ISSUE THREAD

**Issue by arashgm** [cirruslabs/docker-images-flutter#95]
we are getting error on Circle CI on this container that just pushed : cirrusci/flutter:1.20.3

CircleCI was unable to start the container because of a userns remapping failure in Docker.
would you please take a look

**Comment by komarekw** [comment]
here you can finde a bit more details:
`CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 397546 cannot be mapped to a host ID`

**Comment by fkorotkov** [comment]
@arashgm @komarekw could you please provide your Circle config? At least the part where you use the image. This is definitely caused by #93 which fixed #45.

**Comment by arashgm** [comment]
@fkorotkov 

```
docker:
      - image: cirrusci/flutter:1.20.3
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
```
